import React from 'react'

export default (props) => (
  <div className='scroll-text'>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel mauris arcu. Pellentesque eu scelerisque dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam et sapien nec lectus convallis rhoncus id ac augue. Donec ultrices, nisl non blandit facilisis, tellus nisi commodo leo, a eleifend velit velit et dolor. Aenean eleifend nec libero aliquet malesuada. Proin iaculis semper condimentum. Vestibulum suscipit consectetur velit, vel commodo ante scelerisque vitae. Mauris mollis purus ac leo ultrices, et convallis metus ultricies. Nam euismod lorem in risus aliquam laoreet. Nullam id elit in augue tempus efficitur. Praesent bibendum est a eros sodales, eget vulputate tellus vehicula.

Aenean in enim mauris. Vivamus ipsum mauris, tincidunt ac condimentum nec, tincidunt sed odio. Suspendisse euismod urna non dolor ornare venenatis. Pellentesque pretium id elit ac accumsan. Etiam vehicula in diam non euismod. Maecenas congue est id sem varius ultricies. Vestibulum nec dolor sit amet ligula sagittis viverra. Etiam porta arcu magna, a faucibus ante egestas id. Ut eget scelerisque massa.

Donec finibus metus ac dolor tempus, non bibendum sem tempus. Donec sollicitudin ultrices lectus, at posuere mauris congue sit amet. Aliquam neque erat, congue eu dolor et, consequat ultrices velit. Nulla at tortor est. Sed turpis ligula, molestie ac vulputate sit amet, porttitor eget purus. Mauris vitae ultricies lacus, id tempor sem. Duis quis nibh luctus, porttitor ex at, finibus libero. Nunc quis interdum nisl. Ut rutrum commodo mi, vitae ultrices leo molestie quis. Vivamus a dapibus orci.

Morbi non pharetra lorem. Donec condimentum aliquet enim quis lacinia. Vivamus semper dolor lorem, vel hendrerit tortor feugiat quis. Proin sit amet lorem faucibus augue porttitor feugiat accumsan in dui. Suspendisse sollicitudin erat nec ligula vulputate, sed rhoncus justo iaculis. Curabitur feugiat vestibulum tortor nec commodo. Morbi elementum purus nec lorem lacinia, sed tincidunt neque condimentum. Praesent a aliquet ex. Suspendisse rhoncus, quam maximus scelerisque rhoncus, felis neque hendrerit mauris, vitae rutrum nisl ante eu diam. In accumsan magna dictum, rutrum leo nec, ornare odio. Mauris pharetra, justo vitae gravida accumsan, risus erat posuere sapien, in gravida tortor risus ut tortor. Nulla quis semper mi. Nulla facilisis enim nec nisl mollis maximus. Nullam nec luctus velit. Duis auctor urna at consectetur tincidunt. Aenean fermentum auctor dictum.

Fusce sit amet interdum lacus, ac tincidunt leo. Maecenas hendrerit placerat mi, interdum facilisis arcu efficitur quis. Aenean a dolor ut nisl feugiat dictum ut nec tellus. Nam venenatis ultricies bibendum. Phasellus congue, orci sit amet pulvinar interdum, felis arcu laoreet tortor, non dapibus arcu lacus quis libero. Suspendisse ante tortor, sollicitudin eu massa vitae, feugiat sagittis dolor. Donec euismod aliquam ipsum, pellentesque vestibulum est consequat eu. Sed sed ex ullamcorper, dignissim erat sit amet, tristique lectus. Mauris lacinia enim quam, at vehicula metus sagittis eget. Quisque scelerisque pellentesque elit, ut sollicitudin purus hendrerit ut. Nam ante orci, scelerisque et eleifend vel, ultrices ut ex. Nulla quam ante, ullamcorper at porttitor ut, porta sed tellus. Nam rhoncus quam eu neque malesuada, et accumsan nisl sollicitudin.
  </div>
)